# docker-compose.yaml
version: '3.8'
services:
  movie-db:
    build:
      context: .
      dockerfile: Dockerfile.movie-db
    ports:
      - "5001:5001"
      - "8080:8080"
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8081:8081"
    environment:
      - GRPC_SERVER_URL=movie-db:5001
    depends_on:
      - movie-db
