FROM golang:1.21.8-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o ./gateway-service ./grpc/client/client.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway-service .
COPY --from=builder /app/app.properties .

EXPOSE 8081
CMD ["./gateway-service"]