// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0--rc1
// source: movies.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MovieInterface_SearchMovie_FullMethodName = "/grpc.MovieInterface/SearchMovie"
)

// MovieInterfaceClient is the client API for MovieInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieInterfaceClient interface {
	SearchMovie(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type movieInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieInterfaceClient(cc grpc.ClientConnInterface) MovieInterfaceClient {
	return &movieInterfaceClient{cc}
}

func (c *movieInterfaceClient) SearchMovie(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, MovieInterface_SearchMovie_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieInterfaceServer is the server API for MovieInterface service.
// All implementations must embed UnimplementedMovieInterfaceServer
// for forward compatibility
type MovieInterfaceServer interface {
	SearchMovie(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMovieInterfaceServer()
}

// UnimplementedMovieInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedMovieInterfaceServer struct {
}

func (UnimplementedMovieInterfaceServer) SearchMovie(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}
func (UnimplementedMovieInterfaceServer) mustEmbedUnimplementedMovieInterfaceServer() {}

// UnsafeMovieInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieInterfaceServer will
// result in compilation errors.
type UnsafeMovieInterfaceServer interface {
	mustEmbedUnimplementedMovieInterfaceServer()
}

func RegisterMovieInterfaceServer(s grpc.ServiceRegistrar, srv MovieInterfaceServer) {
	s.RegisterService(&MovieInterface_ServiceDesc, srv)
}

func _MovieInterface_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieInterfaceServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieInterface_SearchMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieInterfaceServer).SearchMovie(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieInterface_ServiceDesc is the grpc.ServiceDesc for MovieInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MovieInterface",
	HandlerType: (*MovieInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _MovieInterface_SearchMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movies.proto",
}

const (
	ScreeningNowInterface_MovieNowPlaying_FullMethodName = "/grpc.ScreeningNowInterface/MovieNowPlaying"
)

// ScreeningNowInterfaceClient is the client API for ScreeningNowInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScreeningNowInterfaceClient interface {
	MovieNowPlaying(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*Response, error)
}

type screeningNowInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewScreeningNowInterfaceClient(cc grpc.ClientConnInterface) ScreeningNowInterfaceClient {
	return &screeningNowInterfaceClient{cc}
}

func (c *screeningNowInterfaceClient) MovieNowPlaying(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, ScreeningNowInterface_MovieNowPlaying_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScreeningNowInterfaceServer is the server API for ScreeningNowInterface service.
// All implementations must embed UnimplementedScreeningNowInterfaceServer
// for forward compatibility
type ScreeningNowInterfaceServer interface {
	MovieNowPlaying(context.Context, *PageRequest) (*Response, error)
	mustEmbedUnimplementedScreeningNowInterfaceServer()
}

// UnimplementedScreeningNowInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedScreeningNowInterfaceServer struct {
}

func (UnimplementedScreeningNowInterfaceServer) MovieNowPlaying(context.Context, *PageRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovieNowPlaying not implemented")
}
func (UnimplementedScreeningNowInterfaceServer) mustEmbedUnimplementedScreeningNowInterfaceServer() {}

// UnsafeScreeningNowInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScreeningNowInterfaceServer will
// result in compilation errors.
type UnsafeScreeningNowInterfaceServer interface {
	mustEmbedUnimplementedScreeningNowInterfaceServer()
}

func RegisterScreeningNowInterfaceServer(s grpc.ServiceRegistrar, srv ScreeningNowInterfaceServer) {
	s.RegisterService(&ScreeningNowInterface_ServiceDesc, srv)
}

func _ScreeningNowInterface_MovieNowPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreeningNowInterfaceServer).MovieNowPlaying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScreeningNowInterface_MovieNowPlaying_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreeningNowInterfaceServer).MovieNowPlaying(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScreeningNowInterface_ServiceDesc is the grpc.ServiceDesc for ScreeningNowInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScreeningNowInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ScreeningNowInterface",
	HandlerType: (*ScreeningNowInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MovieNowPlaying",
			Handler:    _ScreeningNowInterface_MovieNowPlaying_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movies.proto",
}
