// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: movies.proto

/*
Package protogen is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package protogen

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_MovieInterface_SearchMovie_0(ctx context.Context, marshaler runtime.Marshaler, client MovieInterfaceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.SearchMovie(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_MovieInterface_SearchMovie_0(ctx context.Context, marshaler runtime.Marshaler, server MovieInterfaceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.SearchMovie(ctx, &protoReq)
	return msg, metadata, err

}

func request_ScreeningNowInterface_MovieNowPlaying_0(ctx context.Context, marshaler runtime.Marshaler, client ScreeningNowInterfaceClient, req *http.Request, pathParams map[string]string) (ScreeningNowInterface_MovieNowPlayingClient, runtime.ServerMetadata, error) {
	var protoReq PageRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.MovieNowPlaying(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterMovieInterfaceHandlerServer registers the http handlers for service MovieInterface to "mux".
// UnaryRPC     :call MovieInterfaceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMovieInterfaceHandlerFromEndpoint instead.
func RegisterMovieInterfaceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MovieInterfaceServer) error {

	mux.Handle("POST", pattern_MovieInterface_SearchMovie_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/grpc.MovieInterface/SearchMovie", runtime.WithHTTPPathPattern("/v0/movies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_MovieInterface_SearchMovie_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MovieInterface_SearchMovie_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterScreeningNowInterfaceHandlerServer registers the http handlers for service ScreeningNowInterface to "mux".
// UnaryRPC     :call ScreeningNowInterfaceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterScreeningNowInterfaceHandlerFromEndpoint instead.
func RegisterScreeningNowInterfaceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ScreeningNowInterfaceServer) error {

	mux.Handle("POST", pattern_ScreeningNowInterface_MovieNowPlaying_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterMovieInterfaceHandlerFromEndpoint is same as RegisterMovieInterfaceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMovieInterfaceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterMovieInterfaceHandler(ctx, mux, conn)
}

// RegisterMovieInterfaceHandler registers the http handlers for service MovieInterface to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMovieInterfaceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterMovieInterfaceHandlerClient(ctx, mux, NewMovieInterfaceClient(conn))
}

// RegisterMovieInterfaceHandlerClient registers the http handlers for service MovieInterface
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MovieInterfaceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MovieInterfaceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MovieInterfaceClient" to call the correct interceptors.
func RegisterMovieInterfaceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MovieInterfaceClient) error {

	mux.Handle("POST", pattern_MovieInterface_SearchMovie_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/grpc.MovieInterface/SearchMovie", runtime.WithHTTPPathPattern("/v0/movies"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MovieInterface_SearchMovie_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MovieInterface_SearchMovie_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_MovieInterface_SearchMovie_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v0", "movies"}, ""))
)

var (
	forward_MovieInterface_SearchMovie_0 = runtime.ForwardResponseMessage
)

// RegisterScreeningNowInterfaceHandlerFromEndpoint is same as RegisterScreeningNowInterfaceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterScreeningNowInterfaceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterScreeningNowInterfaceHandler(ctx, mux, conn)
}

// RegisterScreeningNowInterfaceHandler registers the http handlers for service ScreeningNowInterface to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterScreeningNowInterfaceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterScreeningNowInterfaceHandlerClient(ctx, mux, NewScreeningNowInterfaceClient(conn))
}

// RegisterScreeningNowInterfaceHandlerClient registers the http handlers for service ScreeningNowInterface
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ScreeningNowInterfaceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ScreeningNowInterfaceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ScreeningNowInterfaceClient" to call the correct interceptors.
func RegisterScreeningNowInterfaceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ScreeningNowInterfaceClient) error {

	mux.Handle("POST", pattern_ScreeningNowInterface_MovieNowPlaying_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/grpc.ScreeningNowInterface/MovieNowPlaying", runtime.WithHTTPPathPattern("/v0/nowplaying"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ScreeningNowInterface_MovieNowPlaying_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScreeningNowInterface_MovieNowPlaying_0(annotatedContext, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ScreeningNowInterface_MovieNowPlaying_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v0", "nowplaying"}, ""))
)

var (
	forward_ScreeningNowInterface_MovieNowPlaying_0 = runtime.ForwardResponseStream
)
